### ISSUE TITLE
How do I know if the user chooses to disauthorize?

### ISSUE THREAD

**Issue by axiref** [raychenfj/v-wechat-auth#2]
How do you know if the user opts to reject an authorization message when it pops up?

**Comment by raychenfj** [comment]
@axiref 

Actually, I don't remember there is a choice that a user can choose to accept or reject.

Usually, the authorization process is in silent, without user's notice.

But indeed, there is no way I can know if the user does choose to reject. Actually, I get authorization permission from https://open.weixin.qq.com/connect/oauth2/authorize. When accepted, it redirects to my page, otherwise, I don't think it does anything to notify me there is a rejection, it may just simply close or something.
